### PR TITLE
Use fixed versions

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/49)

### CODE REVIEW

**Comment by alvarezguille** [comment]
___
*[pom.xml, line 65 at r2](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/49#-Ldxc7BKAWjaHumrAAqm:-Ldxc7BKAWjaHumrAAqn:b64qj41) ([raw file](https://github.com/vaadin/vaadin-rich-text-editor-flow/blob/a854b99ab6bc25dccac06feaa1f7de0624c66db4/pom.xml#L65)):*
> ```
> <module>vaadin-rich-text-editor-flow-integration-tests</module>
> ```
how is duplicating a module removing a duplicate declaration?

**Comment by SomeoneToIgnore** [comment]
___
*[vaadin-rich-text-editor-flow-demo/webpack.config.js, line 0 at r3](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/49#-LdxdBhuCSVU9UaGaq5P:-LdxdBhuCSVU9UaGaq5Q:b-y23q3m) ([raw file](https://github.com/vaadin/vaadin-rich-text-editor-flow/blob/340dd997fd1d0044bfc234b7c42f20997036cfe7/vaadin-rich-text-editor-flow-demo/webpack.config.js#L0)):*
Hm, I presume, you should not have those files in the vcs for this project, should you?

**Comment by alvarezguille** [comment]
___
*[pom.xml, line 65 at r2](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/49#-Ldxc7BKAWjaHumrAAqm:-Ldxd4zY8kEj0lL9p4WF:bbtvppn) ([raw file](https://github.com/vaadin/vaadin-rich-text-editor-flow/blob/a854b99ab6bc25dccac06feaa1f7de0624c66db4/pom.xml#L65)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Right, had removed it from the default set of modules
</blockquote></details>

afaik RTE release build took care of that
what's the reason for this kind of changes before release? is it needed?

**Comment by SomeoneToIgnore** [comment]
___
*[pom.xml, line 65 at r2](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/49#-Ldxc7BKAWjaHumrAAqm:-Ldxe42r6bJGng2tVZfG:byreg38) ([raw file](https://github.com/vaadin/vaadin-rich-text-editor-flow/blob/a854b99ab6bc25dccac06feaa1f7de0624c66db4/pom.xml#L65)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

afaik RTE release build took care of that
what's the reason for this kind of changes before release? is it needed?
</blockquote></details>

Not mandatory, just wanted to have a similar structure in projects.
Moved the module back.

**Pull request closed without merging**
